### ISSUE TITLE
ソフトウェアの実行手順

### ISSUE THREAD

**Issue by nkm071** [Tsumoridesu/emcl_with_landmark#1]
環境
ubuntu 18.04

以下の手順でemcl_with_landmarkが動作する．
```
sudo chmod 666 /dev/bus/usb/001/*

roslaunch theta_simple_stitching  theta.launch
 
roslaunch orne_bringup orne_alpha.launch 

roslaunch yolov5_pytorch_ros detector.launch

roslaunch orne_navigation_executor play_waypoints_nav_alpha.launch

roslaunch icart_mini_driver teleop_joy.launch

```

実行の様子
https://drive.google.com/file/d/11FNmalHYtdryx9cdC4g_hUsmDcD5AyZH/view?usp=share_link

参考文献
https://github.com/open-rdc/mcl_with_landmark
https://github.com/open-rdc/orne_navigation

**Comment by Tsumoridesu** [comment]
ここの**YOLO**と**play_waypoints_nav_alpha**は**改造済みのもの**ですので要注意
